package gui;

/*
 Copyright 2014 Jean-Baptiste Lespiau jeanbaptiste.lespiau@gmail.com

 This file is part of Fizzim.

 Fizzim is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 3 of the License, or
 (at your option) any later version.

 Fizzim is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import java.awt.Component;
import java.util.ResourceBundle;

import javax.swing.JDialog;
import javax.swing.JButton;
import javax.swing.Action;

import actions.cancelAction;
import actions.okAction;

import javax.swing.JPanel;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/*
 * TODO : Focus traversal (using tab we can go to the next field)
 * A general window with a content panel and an Ok and Cancel button
 */
/**
 * General editing window composed of a central JPanel and two buttons : an OK
 * and a Cancel buttons.
 * 
 * To use it :
 * - call the constructor to create a general editor
 * - set the central JPanel using setPanel()
 * - complete the display using display()
 * 
 * 
 */
@SuppressWarnings("serial")
public class GeneralEditorWindow extends JDialog {
  private static final ResourceBundle locale =
      ResourceBundle.getBundle("locale.Editors");

  private JButton btnCancel;
  private JButton btnOk;
  private final Action okAction =
      new okAction(this, locale.getString("edit_ok"),
          locale.getString("edit_ok_description"));
  private final Action cancelAction =
      new cancelAction(this, locale.getString("edit_cancel"),
          locale.getString("edit_cancel_description"));
  private JPanel panel;

  private BoxLayout layout = new BoxLayout(getContentPane(), BoxLayout.Y_AXIS);
  private GroupLayout gl_panel_1;

  private Component parent;

  /**
   * 
   * @param parent
   *          The parent component. Used only to set the position of the editing
   *          window at the center of the parent component
   * @param name
   *          Title of the editor Window
   * @param content
   *          Content of the editor window
   */
  public GeneralEditorWindow(Component parent, String name, JPanel content) {

    this.parent = parent;
    /* Initialization of buttons and panels */
    /*
     * /!\ Required to see the design using WindowBuilder :
     * panel = new EdgeEditorPanel();
     * Elswise, use content
     */
    panel = content;
    getContentPane().add(panel);

    JPanel panel_1 = new JPanel();
    getContentPane().add(panel_1);

    btnCancel = new JButton(cancelAction);
    btnOk = new JButton(okAction);

    setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    setTitle(name);
    getRootPane().setDefaultButton(this.btnOk);

    /* Code generated by WindowBuilder */
    getContentPane().setLayout(layout);

    gl_panel_1 = new GroupLayout(panel_1);
    gl_panel_1.setHorizontalGroup(
        gl_panel_1.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, gl_panel_1.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );
    gl_panel_1.setVerticalGroup(
        gl_panel_1.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, gl_panel_1.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(gl_panel_1.createParallelGroup(Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap())
        );
    panel_1.setLayout(gl_panel_1);

    /* End of the code generated by WindowBuilder */
    /* TODO : DOCUMENT_MODAL should be enough but it does not. */
    setModalityType(ModalityType.APPLICATION_MODAL);
  }

  public void setPanel(JPanel comp) {
    assert panel != null && comp != null;
    remove(panel);
    add(comp, 0);
    panel = comp;
  }

  public void display() {
    this.pack();
    setLocationRelativeTo(parent);
    this.setVisible(true);
  }

  /**
   * @return The cancel button to be able to attach actions on it
   */
  public JButton getBtnCancel() {
    return btnCancel;
  }

  /**
   * @return The ok button to be able to attach actions on it
   */
  public JButton getBtnOk() {
    return btnOk;
  }
}
